### ISSUE TITLE
Warning message about package emoa not being installed

### ISSUE THREAD

**Issue by ledell** [a-hanf/mlr3automl#19]
I got a warning about not having the **emoa** package installed; not sure if this is a real issue or not.  Just posting here for reference, in case not having it installed changes/hurts the results (if it's required for hyperband?).

```
> library(mlr3automl)
> iris_task <- tsk('iris')
> model <- AutoML(iris_task)
                 numeric_cols all_cols
no_encoding                 4        4
one_hot_encoding            4        4
impact_encoding             4        4
Warning messages:
1: Package 'emoa' required but not installed for Tuner '<TunerHyperband>'
2: Package 'emoa' required but not installed for Optimizer '<OptimizerChain>'
```

**Comment by a-hanf** [comment]
Thanks for the report!
This was an issue with `mlr3hyperband` and should be fixed with this commit: https://github.com/mlr-org/mlr3hyperband/commit/95a17182ed4129d99dc544aa4bbeebaa204fd210

Try to update `mlr3hyperband` like so:
```
devtools::install_github("mlr-org/mlr3hyperband@95a17182ed4129d99dc544aa4bbeebaa204fd210")
```
This should fix the warning (we did not need `emoa` anyway, it is only used for multi-crit optimisation). Let me know if it helps

**Comment by ledell** [comment]
That fixed it, thanks!
